[tool.poetry]
name = "tutorial-on-networkx"
version = "0.1.0"
description = ""
authors = ["Hiroaki Ogasawara <13391129+xhiroga@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
networkx = "2.5"
matplotlib = "^3.4.1"
decorator = "4.4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app = "app:main"
