[project]
name = "resource-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.9.0",
    "click>=8.2.1",
    "fastmcp>=2.8.1",
    "mcp>=1.9.5.dev14",
    "uvicorn>=0.34.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/resource_link"]

[tool.uv.sources]
mcp = { git = "https://github.com/modelcontextprotocol/python-sdk" }
